# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_histograma.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Histograma(object):
    def setupUi(self, Histograma):
        Histograma.setObjectName("Histograma")
        Histograma.resize(920, 720)
        self.centralwidget = QtWidgets.QWidget(Histograma)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(500, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.grafico_histograma = QtWidgets.QVBoxLayout()
        self.grafico_histograma.setObjectName("grafico_histograma")
        self.verticalLayout_2.addLayout(self.grafico_histograma)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_3.addWidget(self.frame)
        self.gbox_barras = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_barras.setObjectName("gbox_barras")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbox_barras)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.rdb_10 = QtWidgets.QRadioButton(self.gbox_barras)
        self.rdb_10.setObjectName("rdb_10")
        self.horizontalLayout.addWidget(self.rdb_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.rdb_20 = QtWidgets.QRadioButton(self.gbox_barras)
        self.rdb_20.setObjectName("rdb_20")
        self.horizontalLayout.addWidget(self.rdb_20)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.rdb_50 = QtWidgets.QRadioButton(self.gbox_barras)
        self.rdb_50.setObjectName("rdb_50")
        self.horizontalLayout.addWidget(self.rdb_50)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.rdb_personalizado = QtWidgets.QRadioButton(self.gbox_barras)
        self.rdb_personalizado.setObjectName("rdb_personalizado")
        self.horizontalLayout.addWidget(self.rdb_personalizado)
        self.edt_personalizado = QtWidgets.QSpinBox(self.gbox_barras)
        self.edt_personalizado.setMinimumSize(QtCore.QSize(100, 0))
        self.edt_personalizado.setMinimum(1)
        self.edt_personalizado.setMaximum(100)
        self.edt_personalizado.setProperty("value", 10)
        self.edt_personalizado.setObjectName("edt_personalizado")
        self.horizontalLayout.addWidget(self.edt_personalizado)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.gbox_barras)
        Histograma.setCentralWidget(self.centralwidget)

        self.retranslateUi(Histograma)
        QtCore.QMetaObject.connectSlotsByName(Histograma)

    def retranslateUi(self, Histograma):
        _translate = QtCore.QCoreApplication.translate
        Histograma.setWindowTitle(_translate("Histograma", "Histograma de la imagen"))
        self.label.setText(_translate("Histograma", "Histograma"))
        self.gbox_barras.setTitle(_translate("Histograma", "Cantidad de barras"))
        self.rdb_10.setText(_translate("Histograma", "10"))
        self.rdb_20.setText(_translate("Histograma", "20"))
        self.rdb_50.setText(_translate("Histograma", "50"))
        self.rdb_personalizado.setText(_translate("Histograma", "Personalizado"))
